<?php
$ICEcoderUserSettings = array(
"versionNo"		=> "4.0",
"root"			=> "",
"checkUpdates"		=> true,
"openLastFiles"		=> true,
"findFilesExclude"	=> array(".doc",".gif",".jpg",".jpeg",".pdf",".png",".swf",".xml",".zip"),
"codeAssist"		=> true,
"visibleTabs"		=> false,
"lockedNav"		=> true,
"tagWrapperCommand"	=> "ctrl+alt",
"autoComplete"		=> "ctrl+space",
"password"		=> "0f29300f77a8be29893649b62e7bb410e2962d404bd58338d0a7",
"bannedFiles"		=> array(),
"bannedPaths"		=> array("/var/www/.git","/var/www/sites/all/modules","/var/www/sites/default/files"),
"allowedIPs"		=> array("*"),
"theme"			=> "default",
"fontSize"		=> "13px",
"lineWrapping"		=> true,
"indentWithTabs"	=> true,
"indentSize"		=> 4,
"bugFilePaths"		=> array(),
"bugFileCheckTimer"	=> 0,
"bugFileMaxLines"	=> 0,
"pluginPanelAligned"	=> "left",
"plugins"		=> array(),
"previousFiles"		=> "|home|vivainovacao|projetoyao.vivainovacao.com|protected|models|Usuario.php,|home|vivainovacao|projetoyao.vivainovacao.com|protected|controllers|UsuarioController.php,|home|vivainovacao|projetoyao.vivainovacao.com|protected|views|usuario|_form.php",
"last10Files"		=> "|home|vivainovacao|projetoyao.vivainovacao.com|protected|models|Usuario.php,|home|vivainovacao|projetoyao.vivainovacao.com|protected|views|usuario|_form.php,|home|vivainovacao|projetoyao.vivainovacao.com|protected|controllers|UsuarioController.php"
);
?>