-- MySQL Script generated by MySQL Workbench
-- Sex 14 Nov 2014 16:12:35 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `UID` INT NOT NULL,
  `UsuarioNome` VARCHAR(45) NOT NULL,
  `UsuarioPassword` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GrupoAcesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GrupoAcesso` (
  `GID` INT NOT NULL,
  `GrupoNome` VARCHAR(45) NULL,
  PRIMARY KEY (`GID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chave` (
  `NumeroSala` INT NOT NULL,
  PRIMARY KEY (`NumeroSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Porteiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Porteiro` (
  `idPorteiro` INT NOT NULL,
  `PorteiroNome` VARCHAR(45) NULL,
  `Empresa` VARCHAR(45) NULL,
  PRIMARY KEY (`idPorteiro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recurso` (
  `NumeroTombo` INT NOT NULL,
  `Descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`NumeroTombo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Copia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Copia` (
  `NumeroSala` INT NOT NULL,
  `NumeroCopia` INT NOT NULL DEFAULT 1,
  CONSTRAINT `NumeroSala`
    FOREIGN KEY (`NumeroSala`)
    REFERENCES `mydb`.`Chave` (`NumeroSala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pertence_a`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pertence_a` (
  `UID` INT NOT NULL,
  `GID` INT NOT NULL,
  CONSTRAINT `GID`
    FOREIGN KEY (`GID`)
    REFERENCES `mydb`.`GrupoAcesso` (`GID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `UID`
    FOREIGN KEY (`UID`)
    REFERENCES `mydb`.`Usuario` (`UID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tem_acesso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tem_acesso` (
  `GID` INT NOT NULL,
  `NumeroSala` INT NOT NULL,
  CONSTRAINT `GID`
    FOREIGN KEY (`GID`)
    REFERENCES `mydb`.`GrupoAcesso` (`GID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NumeroSala`
    FOREIGN KEY (`NumeroSala`)
    REFERENCES `mydb`.`Chave` (`NumeroSala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Utilizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Utilizacao` (
  `idUtilizacao` INT NOT NULL,
  PRIMARY KEY (`idUtilizacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Registro_Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Registro_Entrega` (
  `UIDentrega` INT NOT NULL,
  `UIDdevolucao` INT NULL,
  `idPort` INT NOT NULL,
  `NumSala` INT NOT NULL,
  `NumCopia` INT NOT NULL,
  `DatetimeEntrega` DATETIME NOT NULL,
  `DatetimeDevolucao` DATETIME NULL,
  `Observacao` TEXT(200) NULL,
  `idUtiliza` INT NULL,
  INDEX `UID_idx` (`UIDentrega` ASC, `UIDdevolucao` ASC),
  INDEX `idUtilzacao_idx` (`idUtiliza` ASC),
  CONSTRAINT `UID`
    FOREIGN KEY (`UIDentrega` , `UIDdevolucao`)
    REFERENCES `mydb`.`Usuario` (`UID` , `UID`)
    ON DELETE NO ACTION
    ON UPDATE SET NULL,
  CONSTRAINT `IdPorteiro`
    FOREIGN KEY (`idPort`)
    REFERENCES `mydb`.`Porteiro` (`idPorteiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NumeroSala`
    FOREIGN KEY (`NumSala`)
    REFERENCES `mydb`.`Copia` (`NumeroSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `NumeroCopia`
    FOREIGN KEY (`NumCopia`)
    REFERENCES `mydb`.`Copia` (`NumeroCopia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUtilzacao`
    FOREIGN KEY (`idUtiliza`)
    REFERENCES `mydb`.`Utilizacao` (`idUtilizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RecUtilzados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RecUtilzados` (
  `idUtilizacao` INT NOT NULL,
  `NumTombo` INT NOT NULL,
  INDEX `idUtilizacao_idx` (`idUtilizacao` ASC),
  INDEX `NumeroTombo_idx` (`NumTombo` ASC),
  CONSTRAINT `NumeroTombo`
    FOREIGN KEY (`NumTombo`)
    REFERENCES `mydb`.`Recurso` (`NumeroTombo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUtilizacao`
    FOREIGN KEY (`idUtilizacao`)
    REFERENCES `mydb`.`Utilizacao` (`idUtilizacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
